name: CI-CD DevOps Proyecto

on:
  push:
    branches:
      - deploy

jobs:
  docker-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 327940345200.dkr.ecr.us-east-1.amazonaws.com

      - name: Build frontend
        run: |
          docker build --build-arg VITE_API_URL=http://innovatech-alb-1247484730.us-east-1.elb.amazonaws.com -t 327940345200.dkr.ecr.us-east-1.amazonaws.com/frontend:latest ./frontend
          docker push 327940345200.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Build backend
        run: |
          docker build -t 327940345200.dkr.ecr.us-east-1.amazonaws.com/backend:latest ./backend
          docker push 327940345200.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      - name: Force ECS deploy
        run: |
          aws ecs update-service \
            --cluster innovatech-cluster \
            --service backend \
            --force-new-deployment